[package]
name = "sky_orm_macros"
version.workspace = true
edition.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8.0"
darling = "0.20.11"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
