[package]
name = "sky-orm-tests"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
chrono = "0.4.41"
sky-orm.workspace = true
sky-orm-macros.workspace = true
